/*
 * img-src API
 *
 * Image processing and delivery API.  A serverless image processing and delivery API built on Cloudflare Workers with parameter-driven image transformation and on-demand transcoding.  ## Features  - **Image Upload**: Store original images in R2 with SHA256-based deduplication - **On-Demand Transformation**: Resize, crop, and convert images via URL parameters - **Format Conversion**: WebP, AVIF, JPEG, PNG output formats - **Path Organization**: Organize images into folders with multiple paths per image - **CDN Caching**: Automatic edge caching for transformed images  ## Authentication  Authenticate using API Keys with `imgsrc_` prefix. Create your API key at https://img-src.io/settings  ## Rate Limiting  - **Free Plan**: 100 requests/minute - **Pro Plan**: 500 requests/minute  Rate limit headers are included in all responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taehun@taehun.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponse {
    /// API key UUID
    #[serde(rename = "id")]
    pub id: String,
    /// Key name
    #[serde(rename = "name")]
    pub name: String,
    /// Key prefix (first 14 chars)
    #[serde(rename = "key_prefix")]
    pub key_prefix: String,
    /// Granted scopes
    #[serde(rename = "scopes")]
    pub scopes: String,
    /// Creation timestamp (Unix epoch)
    #[serde(rename = "created_at")]
    pub created_at: i32,
    /// Last used timestamp (Unix epoch)
    #[serde(rename = "last_used_at", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<i32>,
    /// Expiration timestamp (Unix epoch)
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i32>,
    /// Total requests made with this key
    #[serde(rename = "total_requests")]
    pub total_requests: i32,
}

impl ApiKeyResponse {
    pub fn new(id: String, name: String, key_prefix: String, scopes: String, created_at: i32, total_requests: i32) -> ApiKeyResponse {
        ApiKeyResponse {
            id,
            name,
            key_prefix,
            scopes,
            created_at,
            last_used_at: None,
            expires_at: None,
            total_requests,
        }
    }
}

