/*
 * img-src API
 *
 * Image processing and delivery API.  A serverless image processing and delivery API built on Cloudflare Workers with parameter-driven image transformation and on-demand transcoding.  ## Features  - **Image Upload**: Store original images in R2 with SHA256-based deduplication - **On-Demand Transformation**: Resize, crop, and convert images via URL parameters - **Format Conversion**: WebP, AVIF, JPEG, PNG output formats - **Path Organization**: Organize images into folders with multiple paths per image - **CDN Caching**: Automatic edge caching for transformed images  ## Authentication  Authenticate using API Keys with `imgsrc_` prefix. Create your API key at https://img-src.io/settings  ## Rate Limiting  - **Free Plan**: 100 requests/minute - **Pro Plan**: 500 requests/minute  Rate limit headers are included in all responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taehun@taehun.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CdnUrls {
    /// Original format URL
    #[serde(rename = "original")]
    pub original: String,
    /// WebP format URL
    #[serde(rename = "webp")]
    pub webp: String,
    /// AVIF format URL
    #[serde(rename = "avif")]
    pub avif: String,
    /// JPEG format URL
    #[serde(rename = "jpeg")]
    pub jpeg: String,
    /// PNG format URL
    #[serde(rename = "png")]
    pub png: String,
}

impl CdnUrls {
    pub fn new(original: String, webp: String, avif: String, jpeg: String, png: String) -> CdnUrls {
        CdnUrls {
            original,
            webp,
            avif,
            jpeg,
            png,
        }
    }
}
