/*
 * img-src API
 *
 * Image processing and delivery API.  A serverless image processing and delivery API built on Cloudflare Workers with parameter-driven image transformation and on-demand transcoding.  ## Features  - **Image Upload**: Store original images in R2 with SHA256-based deduplication - **On-Demand Transformation**: Resize, crop, and convert images via URL parameters - **Format Conversion**: WebP, AVIF, JPEG, PNG output formats - **Path Organization**: Organize images into folders with multiple paths per image - **CDN Caching**: Automatic edge caching for transformed images  ## Authentication  Authenticate using API Keys with `imgsrc_` prefix. Create your API key at https://img-src.io/settings  ## Rate Limiting  - **Free Plan**: 100 requests/minute - **Pro Plan**: 500 requests/minute  Rate limit headers are included in all responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taehun@taehun.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignedUrlResponse {
    /// Time-limited signed URL
    #[serde(rename = "signed_url")]
    pub signed_url: String,
    /// Expiration timestamp (Unix epoch)
    #[serde(rename = "expires_at")]
    pub expires_at: i64,
    /// Seconds until expiration
    #[serde(rename = "expires_in_seconds")]
    pub expires_in_seconds: i32,
}

impl SignedUrlResponse {
    pub fn new(signed_url: String, expires_at: i64, expires_in_seconds: i32) -> SignedUrlResponse {
        SignedUrlResponse {
            signed_url,
            expires_at,
            expires_in_seconds,
        }
    }
}
