/*
 * img-src API
 *
 * Image processing and delivery API.  A serverless image processing and delivery API built on Cloudflare Workers with parameter-driven image transformation and on-demand transcoding.  ## Features  - **Image Upload**: Store original images in R2 with SHA256-based deduplication - **On-Demand Transformation**: Resize, crop, and convert images via URL parameters - **Format Conversion**: WebP, AVIF, JPEG, PNG output formats - **Path Organization**: Organize images into folders with multiple paths per image - **CDN Caching**: Automatic edge caching for transformed images  ## Authentication  Authenticate using API Keys with `imgsrc_` prefix. Create your API key at https://img-src.io/settings  ## Rate Limiting  - **Free Plan**: 100 requests/minute - **Pro Plan**: 500 requests/minute  Rate limit headers are included in all responses.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taehun@taehun.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSettingsRequest {
    /// Preferred delivery formats (ordered)
    #[serde(rename = "delivery_formats", skip_serializing_if = "Option::is_none")]
    pub delivery_formats: Option<Vec<String>>,
    /// Default image quality (1-100)
    #[serde(rename = "default_quality", skip_serializing_if = "Option::is_none")]
    pub default_quality: Option<i32>,
    /// Default fit mode
    #[serde(rename = "default_fit_mode", skip_serializing_if = "Option::is_none")]
    pub default_fit_mode: Option<String>,
    /// Default maximum width (null to clear)
    #[serde(rename = "default_max_width", skip_serializing_if = "Option::is_none")]
    pub default_max_width: Option<i32>,
    /// Default maximum height (null to clear)
    #[serde(rename = "default_max_height", skip_serializing_if = "Option::is_none")]
    pub default_max_height: Option<i32>,
    /// UI theme
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    /// UI language
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

impl UpdateSettingsRequest {
    pub fn new() -> UpdateSettingsRequest {
        UpdateSettingsRequest {
            delivery_formats: None,
            default_quality: None,
            default_fit_mode: None,
            default_max_width: None,
            default_max_height: None,
            theme: None,
            language: None,
        }
    }
}
